### ISSUE TITLE
Bug: usernames should always remain in the same order to avoid unnecessary changes

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/pizza-cli#209]
In #208, there are several changes where the order of the GitHub users changes and that's all.

![CleanShot 2024-09-28 at 20 29 18](https://github.com/user-attachments/assets/7b2164b6-749e-4c71-a487-856c57fd898a)

It would be nice to keep the order the same (alphabetical most likely) so that only actual owner changes are applied.

**Comment by jpmcb** [comment]
The idea behind the original implementation is that the order matters: the people with the most changes show up first. This was more or less the easiest solution since we sort the contributors in each file based on their changes and then add the first 3 (where the first person has the most contributions).

**Comment by nickytonline** [comment]
Cool cool. Thanks for the context @jpmcb!

**Comment by udaypatel1** [comment]
@jpmcb – should this issue be closed or handled since it looks like it is resolved?

Just pointing it out to clean up Issues in the backlog.

**Comment by nickytonline** [comment]
I'm going to go ahead and close this for now.
