### ISSUE TITLE
Bug: NPM version mismatch 

### ISSUE THREAD

**Issue by Anush008** [open-sauced/pizza-cli#35]
### Describe the bug

The current manual NPM release, which is at version `0.0.1rc-6`, doesn't share the same version as the GH release. It should've been `0.0.1rc-1`.

### Steps to reproduce

Running
```sh
npm i -g pizza@1.0.0-beta.1
```
works as expected. But,
```sh
npm i -g pizza@0.0.1-rc6
```
doesn't. Due to reason mentioned above.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Yeah, there were some problems with dropping a new package in the NPM registry and we were blocked for a day or two where things drifted quite abit:

https://github.com/open-sauced/pizza-cli/actions/runs/5942196861

this is fine since we're still very roughly hacking on this. We should cut a new release soon so we can roll forward a fix.

**Comment by jpmcb** [comment]
This should be resolved as of the last release 👍🏼
