### ISSUE TITLE
Bug: Getting GLIBC not found errors on Ubuntu

### ISSUE THREAD

**Issue by dominicduffin1** [open-sauced/pizza-cli#70]
### Describe the bug

In the Ubuntu terminal I am seeing ```GLIBC_2.32 not found``` and ```GLIBC_2.34 not found``` errors when trying to run the CLI.

![Screenshot (77)](https://github.com/open-sauced/pizza-cli/assets/26224873/7f89f8b4-0680-43e5-9033-7bb5d53f2202)

### Steps to reproduce

1. Install the CLI in Ubuntu using `npm i -g pizza`
2. Run the `pizza` command

### Browsers

Other (add additional context)

### Additional context (Is this in dev or production?)

The environment is Ubuntu 20.04 (WSL)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by jpmcb** [comment]
Ah, we're not building with `CGO_ENABLED=0`

https://github.com/open-sauced/pizza-cli/blob/ae5a165ed871301b38b2a77ab73463c034c79c47/.github/workflows/release.yaml#L74-L81

this means that the binary that is produced, by default where `CGO_ENABLED` is 1, expects a gcc compiler to be on the system. We should build statically linked binaries since we're not sure what types of dependencies consumers will have on their system.
