### ISSUE TITLE
Bug: `pizza insights contributors` is broken

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#76]
### Describe the bug

Somethings not right with the `insights contributors` command - it just returns all zeros:

```
❯ ./build/pizza insights contributors https://github.com/hashicorp/terraform
Repository URL      https://github.com/hashicorp/terraform
New contributors    0
Recent contributors 0
Alumni contributors 0
Repeat contributors 0
```

### Steps to reproduce

1. Download the latest pizza CLI
2. execute `pizza insights contributors https://github.com/hashicorp/terraform` and notice it's not working as expected

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by k1nho** [comment]
@jpmcb  I think this might because the parameter passed is ```repo.Name``` rather than ```repo.FullName```[here](https://github.com/open-sauced/pizza-cli/blob/fbf424feb9243d203367d354df681e41f1bee2f9/cmd/insights/contributors.go#L231) so its not passing the owner part. I can pick this up! Also unrelated, but found some contributor prs failing on ```show``` due to this one https://github.com/open-sauced/go-api/issues/10
